version: '3.9'

services:
  mariadb:
    image: mariadb:11.5
    container_name: mariadb-symfony
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}   # Root password
      MARIADB_DATABASE: ${MARIADB_DATABASE}               # Name of the database
      MARIADB_USER: ${MARIADB_USER}                                # Username
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}             # User password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx-symfony
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Configuration of Nginx
      - ./public:/var/www/html:ro               # file of the project
    depends_on:
      - mariadb
      - php
    networks:
      - app_network

  php:
    build: ./php
    container_name: php-symfony
    volumes:
      - ./public:/var/www/html
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_symfony
    restart: always
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}  # Root password of MariaDB
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
    driver: local
